{
 "title": "HPA扩容计算",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_labels,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{cluster =~ \"$cluster\"}, namespace)"
    }
   },
   {
    "name": "project_name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace =~ \"$namespace\"}, project_name)"
    }
   },
   {
    "name": "deployment_name",
    "query": {
     "query": "label_values(kube_pod_labels{project_name =~ \"$project_name\"}, deployment_name)"
    }
   },
   { "name": "threshold", "label": "扩容阈值", "query": "0.5" },
   { "name": "mem_rate", "label": "内存水位", "query": "0.8" },
   { "name": "instance_rate", "label": "实例系数", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "HPA扩容情况(CPU)",
   "type": "timeseries",
   "description": "1. 为方便跟使用率曲线匹配,当前实例数/系数(10)；\n2. 扩容阈值根据实际情况填写, vector(扩容阈值)\n3. 扩缩容容忍0.1,在容忍+_0.1范围内均触发扩缩容",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum(irate(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total)  container_cpu_usage_seconds_total{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}/100000) by (pod_name, namespace)) ) / (count(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"}))",
     "legendFormat": "实例当前使用率-$deployment_name"
    },
    {
     "expr": "sum(sum(irate(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total)  container_cpu_usage_seconds_total{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}/100000) by (pod_name, namespace)) ) / (count(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"}) + 1) ",
     "legendFormat": "扩容1个实例后使用率-$deployment_name"
    },
    {
     "expr": "sum(sum(irate(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total)  container_cpu_usage_seconds_total{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}/100000) by (pod_name, namespace)) ) / (count(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"}) + 2) ",
     "legendFormat": "扩容2个实例后使用率-$deployment_name"
    },
    { "expr": "vector(${threshold})*1.1", "legendFormat": "扩容阈值(容忍+0.1)-$deployment_name" },
    { "expr": "vector(${threshold})*0.9", "legendFormat": "扩容阈值(容忍-0.1)-$deployment_name" }
   ]
  },
  {
   "title": "HPA拟扩容情况(内存)",
   "type": "timeseries",
   "description": "1. 为方便跟使用率曲线匹配,当前实例数/系数；\n2. 扩容阈值根据实际情况填写, vector(扩容阈值)\n3. 扩缩容容忍0.1,在容忍+_0.1范围内均触发扩缩容",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total) container_memory_usage_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) / sum(container_spec_memory_limit_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) * count(kube_pod_labels{project_name=\"$project_name\",deployment_name=\"$deployment_name\"}) / (count(kube_pod_labels{project_name=\"$project_name\",deployment_name=\"$deployment_name\"})+1)",
     "legendFormat": "实例数+1当前使用率-$deployment_name"
    },
    { "expr": "vector(${mem_rate})*0.9", "legendFormat": "扩容(容忍-0.1)-$deployment_name" },
    {
     "expr": "sum(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total) container_memory_usage_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) / sum(container_spec_memory_limit_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) ",
     "legendFormat": "实例当前使用率-$deployment_name"
    },
    { "expr": "vector(${mem_rate})*1.1", "legendFormat": "扩容(容忍+0.1)-$deployment_name" }
   ]
  },
  {
   "title": "HPA缩容情况(CPU)",
   "type": "timeseries",
   "description": "1. 为方便跟使用率曲线匹配,当前实例数/系数(10)；\n2. 扩容阈值根据实际情况填写, vector(扩容阈值)\n3. 扩缩容容忍0.1,在容忍+_0.1范围内均触发扩缩容",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(sum(irate(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total)  container_cpu_usage_seconds_total{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}/100000) by (pod_name, namespace)) ) / (count(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"}))",
     "legendFormat": "实例当前使用率-$deployment_name"
    },
    {
     "expr": "sum(sum(irate(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total)  container_cpu_usage_seconds_total{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}/100000) by (pod_name, namespace)) ) / (count(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"}) - 1) ",
     "legendFormat": "缩容1个实例后使用率-$deployment_name"
    },
    { "expr": "vector(${threshold})*1.1", "legendFormat": "缩容阈值(容忍+0.1)-$deployment_name" },
    { "expr": "vector(${threshold})*0.9", "legendFormat": "缩容阈值(容忍-0.1)-$deployment_name" },
    {
     "expr": "sum(sum(irate(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total)  container_cpu_usage_seconds_total{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}[1m])) by (pod_name, namespace) / (sum(container_spec_cpu_quota{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container_name!=\"POD\",container_name!=\"\"}/100000) by (pod_name, namespace)) ) / (count(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"}) - 2) ",
     "legendFormat": "缩容1个实例后使用率-$deployment_name"
    }
   ]
  },
  {
   "title": "HPA拟缩容情况(内存)",
   "type": "timeseries",
   "description": "1. 为方便跟使用率曲线匹配,当前实例数/系数；\n2. 扩容阈值根据实际情况填写, vector(扩容阈值)\n3. 扩缩容容忍0.1,在容忍+_0.1范围内均触发扩缩容",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total) container_memory_usage_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) / sum(container_spec_memory_limit_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) * count(kube_pod_labels{project_name=\"$project_name\",deployment_name=\"$deployment_name\"}) / (count(kube_pod_labels{project_name=\"$project_name\",deployment_name=\"$deployment_name\"})-1)",
     "legendFormat": "实例数-1当前使用率-$deployment_name"
    },
    { "expr": "vector(${mem_rate})*0.9", "legendFormat": "缩容(容忍-0.1)-$deployment_name" },
    {
     "expr": "sum(kube_pod_status_ready{project_name=\"$project_name\",deployment_name=\"$deployment_name\",condition=\"true\"} * on (pod_name) group_right(container_cpu_usage_seconds_total) container_memory_usage_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) / sum(container_spec_memory_limit_bytes{project_name=\"$project_name\",deployment_name=\"$deployment_name\",container=\"\"}) ",
     "legendFormat": "实例当前使用率-$deployment_name"
    },
    { "expr": "vector(${mem_rate})*1.1", "legendFormat": "缩容(容忍+0.1)-$deployment_name" }
   ]
  },
  {
   "title": "当前实例数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count(kube_pod_labels{project_name=\"$project_name\",deployment_name=\"$deployment_name\"})",
     "legendFormat": "实例数"
    }
   ]
  }
 ]
}